[package]
name = "rust-workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
chrono = "0.4.39"
dotenv = "0.15.0"
env_logger = "0.11.6"
log = "0.4.22"
tokio = { version = "1.42.0", features = ["full"] }
