name: Build Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Compose
        run: |
          docker build -t able:latest .

      - name: Upload as Artifact
        uses: ishworkh/container-image-artifact-upload@v2.0.0
        with:
          image: able:latest
